### ISSUE TITLE
Exceptions when parsing a table

### ISSUE THREAD

**Issue by tmattsso** [Artur-/TestCodeGenerator#1]
11:08:16,386 SEVERE [org.vaadin.artur.testcodegenerator.Writer](http-localhost-127.0.0.1-8080-2) failed to create reference object of type com.vaadin.ui.Table: java.lang.NullPointerException
    at com.vaadin.data.util.AbstractBeanContainer.getType(AbstractBeanContainer.java:181) [vaadin-server-7.0.0.jar:7.0.0]
    at org.vaadin.artur.testcodegenerator.Writer.addContainerProperty(Writer.java:268) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.createDataSource(Writer.java:214) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writePropertySetter(Writer.java:586) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentProperties(Writer.java:375) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:185) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.createUIClass(Writer.java:75) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.TestCodeGenerator$1.generateTest(TestCodeGenerator.java:17) [test-code-generator-0.3.0.jar:0.3.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_10]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_10]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_10]
    at java.lang.reflect.Method.invoke(Method.java:601) [rt.jar:1.7.0_10]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleBurst(AbstractCommunicationManager.java:1678) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1564) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleUidlRequest(AbstractCommunicationManager.java:582) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:315) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:201) [vaadin-server-7.0.0.jar:7.0.0]
    at org.vaadin.artur.icepush.ICEPushServlet.service(ICEPushServlet.java:72) [icepush-0.5.4.jar:0.5.4]
    at com.merap.promoren.ui.PromorenServlet.service(PromorenServlet.java:39) [:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_10]

11:08:16,653 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,663 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,675 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,691 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,701 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,706 SEVERE [org.vaadin.artur.testcodegenerator.Writer](http-localhost-127.0.0.1-8080-2) failed to create reference object of type com.vaadin.ui.CustomField: java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) [rt.jar:1.7.0_10]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525) [rt.jar:1.7.0_10]
    at java.lang.Class.newInstance0(Class.java:372) [rt.jar:1.7.0_10]
    at java.lang.Class.newInstance(Class.java:325) [rt.jar:1.7.0_10]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentProperties(Writer.java:356) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:185) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.createUIClass(Writer.java:75) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.TestCodeGenerator$1.generateTest(TestCodeGenerator.java:17) [test-code-generator-0.3.0.jar:0.3.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_10]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_10]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_10]
    at java.lang.reflect.Method.invoke(Method.java:601) [rt.jar:1.7.0_10]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleBurst(AbstractCommunicationManager.java:1678) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1564) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleUidlRequest(AbstractCommunicationManager.java:582) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:315) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:201) [vaadin-server-7.0.0.jar:7.0.0]
    at org.vaadin.artur.icepush.ICEPushServlet.service(ICEPushServlet.java:72) [icepush-0.5.4.jar:0.5.4]
    at com.merap.promoren.ui.PromorenServlet.service(PromorenServlet.java:39) [:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_10]

11:08:16,743 WARNING [org.vaadin.artur.testcodegenerator.Writer](http-localhost-127.0.0.1-8080-2) Don't know how to handle children for org.vaadin.thomas.timefield.TimeField. Leaving out from test.
11:08:16,747 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,755 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,758 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,763 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,772 WARNING [com.vaadin.data.util.AbstractProperty](http-localhost-127.0.0.1-8080-2) You are using Property.toString() instead of getValue() to get the value for a TransactionalPropertyWrapper. This will not be supported starting from Vaadin 7.1 (your debugger might call toString() and cause this message to appear).
11:08:16,863 SEVERE [org.vaadin.artur.testcodegenerator.Writer](http-localhost-127.0.0.1-8080-2) failed to create reference object of type com.vaadin.addon.calendar.ui.Calendar: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_10]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_10]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_10]
    at java.lang.reflect.Method.invoke(Method.java:601) [rt.jar:1.7.0_10]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentProperties(Writer.java:372) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:185) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponentChildren(Writer.java:346) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.writeComponent(Writer.java:186) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.Writer.createUIClass(Writer.java:75) [:0.3.0]
    at org.vaadin.artur.testcodegenerator.TestCodeGenerator$1.generateTest(TestCodeGenerator.java:17) [test-code-generator-0.3.0.jar:0.3.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_10]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_10]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_10]
    at java.lang.reflect.Method.invoke(Method.java:601) [rt.jar:1.7.0_10]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:170) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleBurst(AbstractCommunicationManager.java:1678) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleVariables(AbstractCommunicationManager.java:1564) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.AbstractCommunicationManager.handleUidlRequest(AbstractCommunicationManager.java:582) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:315) [vaadin-server-7.0.0.jar:7.0.0]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:201) [vaadin-server-7.0.0.jar:7.0.0]
    at org.vaadin.artur.icepush.ICEPushServlet.service(ICEPushServlet.java:72) [icepush-0.5.4.jar:0.5.4]
    at com.merap.promoren.ui.PromorenServlet.service(PromorenServlet.java:39) [:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_10]
Caused by: java.lang.NullPointerException
    at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:614) [rt.jar:1.7.0_10]
    at java.text.DateFormat.get(DateFormat.java:772) [rt.jar:1.7.0_10]
    at java.text.DateFormat.getTimeInstance(DateFormat.java:472) [rt.jar:1.7.0_10]
    at com.vaadin.addon.calendar.ui.Calendar.getTimeFormat(Calendar.java:626) [vaadin-calendar-cval-2.0-2.0.0-alpha2.jar:2.0.0-alpha2]
    ... 49 more

**Comment by ghost** [comment]
Likely caused by a container implementation which throws an exception for getType("propertyidNotInContainer")
